dbt_proj:
  outputs:
   dev:
     type: "postgres"
     host: "localhost"
     user: "postgres" #your_username
     password: "a" #your_password
     port: 5432
     dbname: "res" #your_database
     schema: "public" #your_schema
     threads: 4
  target: "dev"