version: 2

sources:
  - name: SC_App1
    schema: SC_App1
    tables:
      - name: bonanalyse
      - name: detailfaculteecoleprofesseur
      - name: faculteecole
      - name: membreexterne
      - name: etablissementuniversitaire
      - name: devis
      # - name: 
