version: 2

sources:
  - name: SC_App1
    schema: SC_App1
    tables:
      - name: bonanalyse
      - name: detailsbonanalyse
      - name: detailfaculteecoleprofesseur
      - name: faculteecole
      - name: membreexterne
      - name: etablissementuniversitaire
      - name: statutconfirmationdemandebonanalyse
      - name: statutconfirmationdossuanalyse
      - name: statutbonanalyse
      - name: users
      - name: devis
      - name: demandeficheanalyse
      - name: specialite
      - name: statutdemandeficheanalyse
      - name: moyenpaiement
      - name: diplome
      - name: detailsdevis
      - name: dossieranalyse
      - name: facturation
      - name: statutdossieranalyse
      - name: statutconfirmationdemandedevis
      - name: etudiant
      - name: detailsficheanalyse
      - name: detailsouschampficheanalysevaleurproposeeficheanalyse
      # - name: souschampficheanalyse
      - name: typechamp
      - name: detailchampficheanalysesouschampficheanalyse
      - name: champficheanalyse
      - name: detailchampficheanalysevaleurproposeeficheanalyse
      - name: valeurproposeeficheanalyse
      - name: ficheanalyse
      - name: pays
      - name: civilite
      - name: laboratoire
      - name: typeanalyse
      - name: souschampficheanalyse
      - name: etablissementnonuniversitaire
      - name: etablissementcaracterecommercial
      - name: etablissementcaractereadministratif
      - name: typeetablissement
      - name: secteur
      - name: service
      - name: detailtypeanalyseunitemesure
      - name: detaillaboratoireunitemesure
      - name: unitemesure
